const API='/api';let token=sessionStorage.getItem('mxsn_token')||'';let data={};const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(path,opt={}){opt.headers={...(opt.headers||{}),...(token?{Authorization:'Bearer '+token}:{})};const r=await fetch(API+path,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'حدث خطأ');return d}
async function login(){try{const d=await api('/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('adminPass').value})});token=d.token;sessionStorage.setItem('mxsn_token',token);show()}catch(e){$('loginMsg').textContent=e.message}}
function show(){$('loginBox').classList.add('hidden');$('dashboard').classList.remove('hidden');loadDashboard();setInterval(()=>loadDashboard(true),10000)}
async function loadDashboard(silent=false){try{data=await api('/admin/dashboard');loadSettings();renderOrders();renderProducts()}catch(e){if(!silent){sessionStorage.removeItem('mxsn_token');token='';$('loginMsg').textContent='انتهت الجلسة، سجّل الدخول مجددًا.';$('loginBox').classList.remove('hidden');$('dashboard').classList.add('hidden')}}}
function loadSettings(){const s=data.settings||{};$('sName').value=s.name||'';$('sTag').value=s.tag||'';$('sDesc').value=s.description||'';$('currency').value=s.currency||'USD';$('paymentProvider').value=s.paymentProvider||'';$('paymentAccount').value=s.paymentAccount||'';$('paymentInstructions').value=s.paymentInstructions||'';$('maintenanceMessage').value=s.maintenanceMessage||'';$('maintenanceState').textContent=s.maintenance?'الصيانة مفعّلة':'المتجر مفتوح'}
async function saveSettings(){try{await api('/admin/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('sName').value.trim(),tag:$('sTag').value.trim(),description:$('sDesc').value.trim(),currency:$('currency').value.trim(),paymentProvider:$('paymentProvider').value.trim(),paymentAccount:$('paymentAccount').value.trim(),paymentInstructions:$('paymentInstructions').value.trim(),maintenanceMessage:$('maintenanceMessage').value.trim()})});loadDashboard()}catch(e){alert(e.message)}}
async function toggleMaintenance(){try{await api('/admin/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({maintenance:!data.settings.maintenance})});loadDashboard()}catch(e){alert(e.message)}}
const statusName=s=>({payment_submitted:'بانتظار المراجعة',paid:'تم البيع',rejected:'مرفوض',refunded:'تم الاسترداد'}[s]||s);
function renderOrders(){const os=data.orders||[];const pending=os.filter(o=>o.status==='payment_submitted').length;$('newBadge').textContent=pending?pending+' جديد':'';$('orders').innerHTML=os.length?os.map(o=>`<div class="order"><div><b>${esc(o.productName)}</b><div>المبلغ: ${esc(o.amount)} ${esc(o.currency||data.settings.currency)} — التحويل: ${esc(o.transferId)}</div>${o.customerName?`<div>العميل: ${esc(o.customerName)}</div>`:''}${o.customerContact?`<div>التواصل: ${esc(o.customerContact)}</div>`:''}<small>${new Date(o.createdAt).toLocaleString('ar')}</small></div><b>${statusName(o.status)}</b><div class="actions">${o.status==='payment_submitted'?`<button class="ok" onclick="setStatus('${o.id}','paid')">تم البيع</button><button class="danger" onclick="setStatus('${o.id}','rejected')">رفض</button>`:''}${o.status==='rejected'?`<button class="secondary" onclick="setStatus('${o.id}','refunded')">تم الاسترداد</button>`:''}${o.status==='paid'&&o.deliveryUrl?`<a class="ok" href="${esc(o.deliveryUrl)}" target="_blank">تسليم/فتح المنتج</a>`:''}</div></div>`).join(''):'<div class="empty">لا توجد طلبات.</div>'}
async function setStatus(id,status){try{await api('/admin/orders/'+encodeURIComponent(id)+'/status',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});loadDashboard()}catch(e){alert(e.message)}}
function renderProducts(){const ps=data.products||[];$('productsAdmin').innerHTML=ps.length?ps.map(p=>`<div class="admin-product"><div><b>${esc(p.name)}</b><div>${esc(p.price)} ${esc(p.currency)}</div><small>${p.fileName?'📄 ملف مرفوع':'⚠️ لا يوجد ملف'}</small></div><div class="actions"><button class="secondary" onclick="editProduct('${p.id}')">تعديل</button><button class="danger" onclick="deleteProduct('${p.id}')">حذف</button></div></div>`).join(''):'<div class="empty">لا توجد منتجات.</div>'}
function newProduct(){ $('editor').classList.remove('hidden');$('editorTitle').textContent='إضافة منتج';['pId','pName','pPrice','pCurrency','pImage','pDesc','pFile'].forEach(x=>$(x).value='');$('pCurrency').value=data.settings.currency||'USD';$('editorMsg').textContent=''}
function editProduct(id){const p=data.products.find(x=>x.id===id);newProduct();$('editorTitle').textContent='تعديل المنتج';$('pId').value=p.id;$('pName').value=p.name;$('pPrice').value=p.price;$('pCurrency').value=p.currency;$('pImage').value=p.imageUrl;$('pDesc').value=p.description}
async function saveProduct(){const fd=new FormData();const fields={name:$('pName').value.trim(),price:$('pPrice').value,currency:$('pCurrency').value.trim(),imageUrl:$('pImage').value.trim(),description:$('pDesc').value.trim()};Object.entries(fields).forEach(([k,v])=>fd.append(k,v));if($('pFile').files[0])fd.append('file',$('pFile').files[0]);try{const id=$('pId').value;await api(id?'/admin/products/'+id:'/admin/products',{method:id?'PUT':'POST',body:fd});closeEditor();loadDashboard()}catch(e){$('editorMsg').textContent=e.message}}
async function deleteProduct(id){if(!confirm('حذف المنتج؟'))return;try{await api('/admin/products/'+id,{method:'DELETE'});loadDashboard()}catch(e){alert(e.message)}}function closeEditor(){$('editor').classList.add('hidden')}
if(token)show();
