const API='/api';let state={settings:{},products:[]},selected=null;const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function loadStore(){try{const r=await fetch(API+'/store');if(!r.ok)throw new Error('تعذر الاتصال');state=await r.json();render()}catch(e){$('products').innerHTML='<div class="empty">تعذر الاتصال بالخادم. تأكد من تشغيل Backend.</div>'}}
function render(){const s=state.settings||{};$('storeName').textContent=s.name||'MXSN Nexus';$('storeTag').textContent=s.tag||'متجر المنتجات الرقمية';$('storeTitle').textContent=s.name||'MXSN Nexus';$('storeDescription').textContent=s.description||'';$('year').textContent=new Date().getFullYear();const q=$('search').value.toLowerCase().trim();const ps=(state.products||[]).filter(p=>(p.name+' '+p.description).toLowerCase().includes(q));$('count').textContent=ps.length+' منتج';$('products').innerHTML=ps.map(p=>`<article class="card">${p.imageUrl?`<img src="${esc(p.imageUrl)}" alt="">`:'<div class="placeholder">MXSN</div>'}<div class="card-body"><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><strong>${esc(p.price)} ${esc(p.currency||s.currency||'USD')}</strong><button class="primary" onclick="openBuy('${p.id}')">شراء</button><button class="secondary" onclick="shareProduct('${p.id}')">مشاركة</button></div></article>`).join('')||'<div class="empty">لا توجد منتجات.</div>'}
function openBuy(id){selected=state.products.find(p=>p.id===id);if(!selected)return;$('buyProduct').innerHTML=`<h3>${esc(selected.name)}</h3><p>${esc(selected.price)} ${esc(selected.currency||state.settings.currency||'USD')}</p>`;$('paymentInfo').textContent=[state.settings.paymentProvider,state.settings.paymentAccount,state.settings.paymentInstructions].filter(Boolean).join(' — ');$('amount').value=selected.price;$('transferId').value='';$('customerName').value='';$('customerContact').value='';$('buyMsg').textContent='';$('buyModal').classList.remove('hidden')}
function closeBuy(){$('buyModal').classList.add('hidden')}function openTrack(){$('trackModal').classList.remove('hidden')}function closeTrack(){$('trackModal').classList.add('hidden')}
async function submitOrder(){const body={productId:selected.id,transferId:$('transferId').value.trim(),amount:Number($('amount').value),customerName:$('customerName').value.trim(),customerContact:$('customerContact').value.trim()};if(!body.transferId||!body.amount){$('buyMsg').textContent='أدخل رقم التحويل والمبلغ.';return}try{const r=await fetch(API+'/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر إرسال الطلب');$('buyMsg').innerHTML=`تم إرسال الطلب بنجاح.<br>رقم الطلب: <b>${esc(d.orderId)}</b><br>احتفظ به لمتابعة حالة الطلب.`}catch(e){$('buyMsg').textContent=e.message}}
async function trackOrder(){const id=$('orderIdInput').value.trim();if(!id)return;$('trackMsg').textContent='جاري البحث...';try{const r=await fetch(API+'/orders/'+encodeURIComponent(id)),d=await r.json();if(!r.ok)throw new Error(d.error);const labels={payment_submitted:'بانتظار مراجعة الدفع',paid:'تم البيع — المنتج جاهز',rejected:'تم رفض الطلب',refunded:'تم الاسترداد'};$('trackMsg').innerHTML=`المنتج: ${esc(d.productName)}<br>الحالة: <b>${esc(labels[d.status]||d.status)}</b>${d.deliveryUrl?`<br><a class="ok" href="${esc(d.deliveryUrl)}">تحميل المنتج</a>`:''}`}catch(e){$('trackMsg').textContent=e.message}}
async function shareProduct(id){const p=state.products.find(x=>x.id===id);if(!p)return;const data={title:p.name,text:p.description,url:location.origin+'/#product-'+p.id};try{if(navigator.share)await navigator.share(data);else await navigator.clipboard.writeText(data.url);alert('تم تجهيز رابط المشاركة.')}catch{}}
$('search').oninput=render;loadStore();
